// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';

const SUPABASE_URL = "https://qbtcuzteevpuslnorywd.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InFidGN1enRlZXZwdXNsbm9yeXdkIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTI5NzQ3MzMsImV4cCI6MjA2ODU1MDczM30.X1nWBI33PZsmcu6ipXnSkbRa-MaF-z0UzN66d6WM1GE";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);